### ISSUE TITLE
100% score isn't airdropping NFTs 😟

### ISSUE THREAD

**Issue by mayeenulislam** [LearnWeb3DAO/Freshman-Track#23]
Submitting quiz shows "airdropping NFTs" but immediately after shows "You already have an NFT for this course/lesson"

![learnweb3](https://user-images.githubusercontent.com/4551598/206920241-cb268192-991c-446f-b437-d9ed4b89dc3b.gif)

**Comment by yanukadeneth99** [comment]
Hey @mayeenulislam, could you go into [your Profile](https://learnweb3.io/profiles/my), and confirm that you do not have the NFT there?

**Comment by mayeenulislam** [comment]
There is no NFT in my profile, neither visible in the [public profile](https://learnweb3.io/profiles/mayeenulislam), though I've completed till step 5 of Freshman.

![Profile](https://user-images.githubusercontent.com/4551598/207062770-bbdb84d7-eb1d-4094-b276-9e7fdc009131.png)

**Comment by tkiddo** [comment]
> Submitting quiz shows "airdropping NFTs" but immediately after shows "You already have an NFT for this course/lesson"
> 
> ![learnweb3](https://user-images.githubusercontent.com/4551598/206920241-cb268192-991c-446f-b437-d9ed4b89dc3b.gif) [ ![learnweb3](https://user-images.githubusercontent.com/4551598/206920241-cb268192-991c-446f-b437-d9ed4b89dc3b.gif) ](https://user-images.githubusercontent.com/4551598/206920241-cb268192-991c-446f-b437-d9ed4b89dc3b.gif) [ ](https://user-images.githubusercontent.com/4551598/206920241-cb268192-991c-446f-b437-d9ed4b89dc3b.gif)

same problem。

**Comment by yanukadeneth99** [comment]
Hey @mayeenulislam and @tkiddo, NFTs are paused at the moment so you can claim them once they are resumed. You can continue the learning journey and claim them later. 

I'm locking this conversation until this gets resolved.

**Comment by yanukadeneth99** [comment]
This is resolved now.
