### ISSUE TITLE
{Need Changes] Goerli Faucet (ChainLink) from Build your own cryptocurrency using ERC-20 tokens

### ISSUE THREAD

**Issue by rohitverse** [LearnWeb3DAO/Freshman-Track#36]
Goerli Faucet -- Build your own cryptocurrency using ERC-20 tokens
![image](https://user-images.githubusercontent.com/67726628/222648487-21e419a3-925a-4b74-9a7e-d16b5550e1fb.png)

ChainLink Doesn't Provide Goerli Faucet on their website [Click here to check chainlink faucet](https://faucets.chain.link/)
They Now only Provide Chainlink LINK Faucet on thier Website.

Check here
![image](https://user-images.githubusercontent.com/67726628/222648566-fcfec622-3f53-460a-b8b8-8a412948b826.png)

Please Change Link with Another Goerli Faucet Provider

**Comment by yanukadeneth99** [comment]
Approved the relevant PR #37. Closing this issue.
