### ISSUE TITLE
Dark text color over dark background in Light-Mode

### ISSUE THREAD

**Issue by areenoverclouds** [LearnWeb3DAO/Freshman-Track#5]
### Description
The login-page text (on the black div background) does not change text colour from black to white in light mode. This hinders text readability.
The same problem arises on the first page after verifying the email.

#### Screenshots
![image](https://user-images.githubusercontent.com/46225470/186851775-ed516b1f-8d9c-452c-924f-7eae70c9cb89.png)
![image](https://user-images.githubusercontent.com/46225470/186857510-129223cb-d41c-4e97-b2a6-fab7261af81b.png)
![image](https://user-images.githubusercontent.com/46225470/186858060-ca55c815-c3b9-4d0d-8fa8-5cc790e64725.png)

### To Reproduce
Start the 'Freshman' progression track.
The login page appears. View the page in light mode (Image 1).
Enter and submit the Email-id (Image 2).
Verify your Email-id (Image 3).

**Comment by shubham16598** [comment]
Hi Team,
Can I take up this issue?

**Comment by yanukadeneth99** [comment]
Sorry for the delay @areenoverclouds, it's fixed now. 

<img width="639" alt="Screenshot 2022-11-17 at 1 24 06 AM" src="https://user-images.githubusercontent.com/61384503/202280862-03ccd164-9c9e-4dba-8e2b-66cee5669343.png">
